name: flutter_basic_pro
description: A Flutter Basic project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # https://pub.flutter-io.cn/packages/dio -- 网络请求库
  dio: ^4.0.0

  # https://pub.flutter-io.cn/packages/animations
  animations: ^2.0.1

  # https://pub.flutter-io.cn/packages/fish_redux -- 状态管理框架
  fish_redux: ^0.3.7

  # https://pub.flutter-io.cn/packages/flutter_bloc -- 非常优秀的Widgets框架，特此记录学习使用
  flutter_bloc: ^7.2.0

  # https://pub.flutter-io.cn/packages/group_list_view -- 分组list组件
  group_list_view: ^1.1.1

  # https://pub.flutter-io.cn/packages/flutter_swiper -- swiper组件
  flutter_swiper: ^1.1.6

  # https://pub.flutter-io.cn/packages/shared_preferences -- 本地持久化插件
  shared_preferences: ^2.0.7

  # https://pub.flutter-io.cn/packages/intl -- 国际化
  intl: ^0.17.0

  # https://pub.flutter-io.cn/packages/fluttertoast -- toast弹框
  fluttertoast: ^8.0.8

  # https://pub.flutter-io.cn/packages/flutter_screenutil -- 屏幕适配
  flutter_screenutil: ^5.0.0+2

  # https://pub.flutter-io.cn/packages/flutter_spinkit -- 加载等待框
  flutter_spinkit: ^5.1.0

  # https://pub.flutter-io.cn/packages/url_launcher -- 启动URL的Flutter插件。支持网络，电话，短信和电子邮件
  url_launcher: ^6.0.10

  # https://pub.flutter-io.cn/packages/vercoder_inpute -- 验证码输入框
  vercoder_inputer: ^0.9.0

  # https://pub.flutter-io.cn/packages/flutter_slidable -- cell测滑
  flutter_slidable: ^0.6.0

  # https://pub.flutter-io.cn/packages/image_picker -- 图片选择（相册或拍照）
  image_picker: ^0.8.4+1

  # https://pub.flutter-io.cn/packages/flutter_webview_plugin -- webview展示
  flutter_webview_plugin: ^0.4.0

  # https://pub.flutter-io.cn/packages/transparent_image -- 透明图片控件
  transparent_image: ^2.0.0

  # https://pub.flutter-io.cn/packages/syncfusion_flutter_charts-- 统计图表
  syncfusion_flutter_charts: ^19.2.62 # charts_flutter: ^0.11.0

  # https://pub.flutter-io.cn/packages/fl_chart
  fl_chart: ^0.40.0

  # https://pub.flutter-io.cn/packages/path_provider -- 获取系统文件
  path_provider: ^2.0.4

  # https://pub.flutter-io.cn/packages/cached_network_image -- 加载网络图片并本地缓存
  cached_network_image: ^3.1.0

  # https://pub.flutter-io.cn/packages/sqflite -- 数据库操作
  sqflite: ^2.0.0+4 #不支持web

  # https://pub.flutter-io.cn/packages/pull_to_refresh -- 下拉刷新上拉加载
  pull_to_refresh: ^2.0.0
  # https://pub.flutter-io.cn/packages/flutter_easyrefresh -- 也是上拉刷新和下拉加载
  # flutter_easyrefresh: ^2.2.1

  # https://pub.flutter-io.cn/packages/video_player -- 视频播放
  video_player: ^2.2.3

  # https://pub.flutter-io.cn/packages/device_info -- 获取手机信息
  device_info: ^2.0.2


  # https://pub.flutter-io.cn/packages/flutter_svg -- svg图标控件
  flutter_svg: ^0.22.0

  # https://pub.flutter-io.cn/packages/connectivity -- 网络链接状态
  connectivity: ^3.0.6

  # https://pub.flutter-io.cn/packages/flutter_staggered_grid_view -- 瀑布流
  flutter_staggered_grid_view: ^0.4.0

  # https://pub.flutter-io.cn/packages/get -- 有待探索
  get: ^4.3.8

  # https://pub.flutter-io.cn/packages/material_floating_search_bar -- navtigation上的searchbar
  material_floating_search_bar: ^0.3.4

  # https://pub.flutter-io.cn/packages/dropdown_search -- 搜索下拉框
  dropdown_search: ^1.0.0

  # https://pub.flutter-io.cn/packages/flutter_image_compress -- 图片压缩
  flutter_image_compress: ^1.1.0

  # https://pub.flutter-io.cn/packages/flutter_app_badger -- 桌面icon角标
  flutter_app_badger: ^1.3.0

  # https://pub.flutter-io.cn/packages/flutter_local_notifications -- 通知栏消息提示
  flutter_local_notifications: #设置通知栏消息提示

  # https://pub:flutter-io:cn/packages/dragablegridview_flutter -- 可拖拽，比如标签列表
  dragablegridview_flutter: ^0.2.5

  # https://pub.flutter-io.cn/packages/common_utils -- 工具集合
  flustars: ^2.0.1

  # https://pub.flutter-io.cn/packages/flutter_picker
  flutter_picker: ^2.0.2

  # https://pub.flutter-io.cn/packages/datetime_picker_formfield
  datetime_picker_formfield: ^2.0.0

  # https://pub.flutter-io.cn/packages/persistent_bottom_nav_bar
  persistent_bottom_nav_bar: ^4.0.2

  # https://pub.flutter-io.cn/packages/flutter_native_splash
  flutter_native_splash: ^1.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
